---
#-------------------------------
# General Site Settings

title: H3yon
logo:
author: h3yon
description: this is h3yon's github blog
email: khykhy1006@gmail.com
phone: +82 010-3354-3945
address: Seoul, Korea
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! <br> I’m h3yon <br> Backend Engineer

social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-dribbble", link: "#" }
  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Nice to see you! <br> I am h3yon <br> I am interested in new technology and backend.

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "충분한 자료조사를 거친 뒤, 정확한 일처리를 위하여 계획을 세웁니다."

  - title: "Develop"
    icon: "assets/images/icons/design.png"
    content: "무언가에 도전하는 것을 좋아하며, 신기술을 적용하여 개발하는 것을 좋아합니다."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "적당한 플랫폼을 사용하여 눈에 보기 편하도록 자료를 정리합니다."

# My Team Section
#team:
#  - title: "Teams"
#    image: "assets/images/team/member-1.png"
#    designation: "Project Manager"
#
#
##-------------------------------
## Skills Section

skills-title: Skills
skills:
  - { name: PPT Presentation, color: "#fdb157", value: "90%" }
  - { name: Java, color: "#9473e6", value: "40%" }
  - { name: Node.js, color: "#bdecf6", value: "80%" }
  - { name: Communication, color: "#ffbcaa", value: "80%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - { name: Linkmoa, icon: "icon-1.png", date: "2021", organization: "MakeUS" }
  - { name: K-Shield Jr, icon: "icon-2.png", date: "2021", organization: "Security Educaton Center" }
  - { name: Security Information Tutor, icon: "icon-3.png", date: "2020", organization: "Seoul Women's Univ" }

#-------------------------------
# Education Section

education-title: Activity
education:
  - { name: K-Shield Jr, date: "2021", organization: "Information Security Education Center" }
  - { name: Information Security Department, date: "2018", organization: "Seoul women's University" }
  - { name: Rising Programmer2, date: "2021", organization: "Cardiff School" }
  - { name: MakeUS  Secretary General, date: "2021", organization: "MakeUS, Profitable Application Development" }

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: Linkmoa,
      icon: ti-palette,
      description: "Whenever you want, you can store links",
      active: # Add true to select section
    }
  - {
      name: Covaccting,
      icon: ti-vector,
      description: "communicate about vaccines against covid virus",
      active: true, # Add true to select section
    }
  - {
      name: Bunjang,
      icon: ti-panel,
      description: "Clone Coding about Bunjang",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "Back-end", type: "backend" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "backend"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "backend"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "h3yon"
    image: "assets/images/testimonial/test22222.jpeg"
    designation: "backend engineer"
    content: "Hi I'm h3yon"

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: h3yon@gmail.com
